### ISSUE TITLE
self.idr_iupred() got stuck

### ISSUE THREAD

**Issue by chaofreddy** [Guido497/phase-separation#2]
It looks like this happened to me and it got stuck there forever:

```
self.fasta2df(dbfasta)
20598
0.39s self.fasta2df(dbfasta)
self.amino_acid_analysis()
100%
20598/20598 [00:24<00:00, 839.45it/s]
26.3s self.amino_acid_analysis()
self.idr_iupred()
0%
0/20598 [00:00<?, ?it/s]
```

Could you check what is going on? Any suggestions are appreciated,

**Comment by Guido497** [comment]
Could you let me know how you imported the iupred2a module, and if this all goes without errors?

And what is the layout of your fasta file, could you maybe deposit the first few lines of that file here?

**Comment by LZhang98** [comment]
Hi, I believe I'm experiencing the same error. The error log shows:

`FileNotFoundError: [Errno 2] No such file or directory: '/path/to/phase-separation/predict_using_pretrained_model/data/iupred2_long_energy_matrix'`

I imported iupred2a as the following:

`import iupred2a_lib as iupred2a`

Here are the first few lines of the proteome fasta I am using:

```
>tr|A0A075B6Y1|A0A075B6Y1_HUMAN T cell receptor alpha joining 30 (Fragment) OS=Homo sapiens OX=9606 GN=TRAJ30 PE=4 SV=1
XNRDDKIIFGKGTRLHILP
>tr|A0A3B3IRS2|A0A3B3IRS2_HUMAN Keratin-associated protein 21-1-like OS=Homo sapiens OX=9606 GN=LOC647264 PE=4 SV=1
MCCNYYGNSCGYGSSYGCGYGSGYGCGYGSSYGCGYGSGYGCGYGSSYGCGYGSGYSCGY
GSGSGCGYGTGYGCGYGCGYGTGYGCGCGSGSGYCGYRPFCFRRCYSSC
>sp|A5D8W1|CFA69_HUMAN Cilia- and flagella-associated protein 69 OS=Homo sapiens OX=9606 GN=CFAP69 PE=1 SV=3
MWTEEAGATAEAQESGIRNKSSSSSQIPVVGVVTEDDEAQDVFKPMDLNRVIKLLEETDK
DGLEEKQLKFVKKLVQCYQNGLPLRDLAQIFKILNLCSGKIKNQPRFIESAYDIIKLCGL
PFLKKKVSDEITYAEDTANSIALLGDLMKIPSSELRIQICKCIVDFYHAEPPKKHIPGYQ
QASSSYKIQMAEVGGLAKTMVQSMTLLENQLVEKLWVLKVLQHLSTSEVNCTIMMKAQAA
```

**Comment by Guido497** [comment]
Did you set the path correctly? You'd have to adapt the '/path/to/phase-separation/' to the correct working directory
